services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: saim_portfolio
      POSTGRES_USER: saim_app
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata:
